import { Municipality } from '../departaments/municipality';
import { User } from '../user/user';
import { GeneralData } from './general-data';
import { Stretch } from './stretch';

export interface Bridge {
  bridgeId?: number;
  name?: string;
  code?: null;
  route?: null;
  mileage?: null;
  pavedRoute?: null;
  horizontalAlignment?: null;
  skew?: null;
  northUtmCoordinates?: null;
  eastUtmCoordinates?: null;
  populationBefore?: null;
  populationAfter?: null;
  status?: string;
  trafficLight?: null;
  evaluationStartDate?: Date;
  evaluationEndDate?: Date;
  long1?: null;
  lat?: null;
  type?: null;
  extra?: null;
  stretchList?: Stretch[];
  imageList?: any[];
  blueprintList?: any[];
  stapesList?: any[];
  commentList?: any[];
  sensorList?: any[];
  channelChannelId?: null;
  generalDataGeneralDataId?: GeneralData;
  municipalityMunicipalityId?: Municipality;
  nonStructuralElementsNonStructuralElementsId?: null;
  otherOtherId?: null;
  pilePileId?: null;
  superstructureSuperstructureId?: null;
  user?: User | null;
}
